public enum Position {
    GOALKEEPER,
    CENTER_BACK,
    FULLBACK,
    LEFT_BACK,
    RIGHT_BACK,
    MIDFILDER,
    LEFT_MIDFILDER,
    RIGHT_MIDFILDER,
    DEFENSIVE_MIDFILDER,
    ATTACKING_MIDFILDER,
    PLAYMAKER,
    CENTER_FORWARD,
    STRIKER,
    WING
}
